#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App2.Droid.Resource", IsApplication=true)]

namespace App2.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060015
			public const int accountContainer = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int accountNameEdit = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int applicationNameTextView = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int balanceTextView = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int imageView1 = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout1 = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout2 = 2131099660;
			
			// aapt resource value: 0x7f060014
			public const int loginButton = 2131099668;
			
			// aapt resource value: 0x7f060006
			public const int logoutButton = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int offlineNotice = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int passwordEdit = 2131099666;
			
			// aapt resource value: 0x7f06001a
			public const int passwordPadTable = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int passwordTextView = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int primaryContainer = 2131099670;
			
			// aapt resource value: 0x7f06000d
			public const int refreshButton = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int retryButton = 2131099656;
			
			// aapt resource value: 0x7f060013
			public const int savePasswordCheckbox = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int splashImageView = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int textView11 = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int textView7 = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int transferAmountEditText = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int transferButton = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int userNameView = 2131099653;
			
			// aapt resource value: 0x7f060018
			public const int verificationEditText = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int verificationImageView = 2131099671;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AccountProfile = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Bootstrapping = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CardManagement = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Empty = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PasswordPadImageButton = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int VerificationCodeInput = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int XjtuCardPassword = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int PasswordPadDigitButton = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
