#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App2.Droid.Resource", IsApplication=true)]

namespace App2.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int accountContainer = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int accountNameEdit = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int applicationNameTextView = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int balanceTextView = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int imageView1 = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout2 = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int loginButton = 2131034128;
			
			// aapt resource value: 0x7f050005
			public const int logoutButton = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int passwordEdit = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int primaryContainer = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int savePasswordCheckbox = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int textView11 = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int textView7 = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int transferAmountEditView = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int transferButton = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int userNameView = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AccountProfile = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CardManagement = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Empty = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
